// Code generated by MockGen. DO NOT EDIT.
// Source: internal/gophermart/repository/tmp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgx "github.com/jackc/pgx/v5"
)

// MockDBPool is a mock of DBPool interface.
type MockDBPool struct {
	ctrl     *gomock.Controller
	recorder *MockDBPoolMockRecorder
}

// MockDBPoolMockRecorder is the mock recorder for MockDBPool.
type MockDBPoolMockRecorder struct {
	mock *MockDBPool
}

// NewMockDBPool creates a new mock instance.
func NewMockDBPool(ctrl *gomock.Controller) *MockDBPool {
	mock := &MockDBPool{ctrl: ctrl}
	mock.recorder = &MockDBPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBPool) EXPECT() *MockDBPoolMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockDBPool) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx, txOptions)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockDBPoolMockRecorder) BeginTx(ctx, txOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockDBPool)(nil).BeginTx), ctx, txOptions)
}
