// Code generated by MockGen. DO NOT EDIT.
// Source: withdrawal_test.go

// Package withdrawal is a generated GoMock package.
package withdrawal

import (
	context "context"
	http "net/http"
	reflect "reflect"

	entity "github.com/MxTrap/gophermart/internal/gophermart/entity"
	gomock "github.com/golang/mock/gomock"
)

// Mockwithdrawer is a mock of withdrawer interface.
type Mockwithdrawer struct {
	ctrl     *gomock.Controller
	recorder *MockwithdrawerMockRecorder
}

// MockwithdrawerMockRecorder is the mock recorder for Mockwithdrawer.
type MockwithdrawerMockRecorder struct {
	mock *Mockwithdrawer
}

// NewMockwithdrawer creates a new mock instance.
func NewMockwithdrawer(ctrl *gomock.Controller) *Mockwithdrawer {
	mock := &Mockwithdrawer{ctrl: ctrl}
	mock.recorder = &MockwithdrawerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockwithdrawer) EXPECT() *MockwithdrawerMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *Mockwithdrawer) GetAll(ctx context.Context, userID int64) ([]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx, userID)
	ret0, _ := ret[0].([]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockwithdrawerMockRecorder) GetAll(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*Mockwithdrawer)(nil).GetAll), ctx, userID)
}

// MockauthMiddleware is a mock of authMiddleware interface.
type MockauthMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockauthMiddlewareMockRecorder
}

// MockauthMiddlewareMockRecorder is the mock recorder for MockauthMiddleware.
type MockauthMiddlewareMockRecorder struct {
	mock *MockauthMiddleware
}

// NewMockauthMiddleware creates a new mock instance.
func NewMockauthMiddleware(ctrl *gomock.Controller) *MockauthMiddleware {
	mock := &MockauthMiddleware{ctrl: ctrl}
	mock.recorder = &MockauthMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthMiddleware) EXPECT() *MockauthMiddlewareMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockauthMiddleware) Validate(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockauthMiddlewareMockRecorder) Validate(next interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockauthMiddleware)(nil).Validate), next)
}
