env: "local"
jwt_secret: "very secret"
token:
  max_count: 5
  ttl:
    access: 1h
    refresh: 1440h
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  database: gophermart
  migration_path: "../migrations"
http:
  host: localhost
  port: 8080
  timeout: 10h
